import { Category, Product } from './types';

export const CATEGORIES: Category[] = [
  { id: 'headphones', name: 'Headphones', nameBn: 'হেডফোন', iconName: 'Headphones', itemCount: 24 },
  { id: 'mice', name: 'Gaming Mice', nameBn: 'গেমিং মাউস', iconName: 'Mouse', itemCount: 18 },
  { id: 'keyboards', name: 'Keyboards', nameBn: 'কীবোর্ড', iconName: 'Keyboard', itemCount: 15 },
  { id: 'chargers', name: 'Fast Chargers', nameBn: 'ফাস্ট চার্জার', iconName: 'Zap', itemCount: 32 },
  { id: 'finger-sleeves', name: 'Finger Sleeves', nameBn: 'ফিঙ্গার স্লিক', iconName: 'Hand', itemCount: 12 },
  { id: 'cables', name: 'Cables', nameBn: 'কেবলস', iconName: 'Cable', itemCount: 40 },
  { id: 'soundboxes', name: 'Soundboxes', nameBn: 'সাউন্ডবক্স', iconName: 'Speaker', itemCount: 16 },
  { id: 'trimmers', name: 'Trimmers', nameBn: 'ট্রিমার', iconName: 'Scissors', itemCount: 10 },
];

export const PRODUCTS: Product[] = [
  // 1. Headphones
  {
    id: 'prod-1',
    name: 'Fantech HG11 Captain 7.1 Gaming Headset',
    nameBn: 'ফ্যানটেক HG11 ক্যাপ্টেন ৭.১ গেমিং হেডসেট',
    category: 'headphones',
    categoryBn: 'হেডফোন',
    price: 2450,
    originalPrice: 3200,
    discountBadge: '-23%',
    rating: 4.9,
    reviewCount: 142,
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    description: 'High performance RGB surround sound gaming headset with noise-canceling microphone.',
    descriptionBn: 'উচ্চমানের আরজিবি সারাউন্ড সাউন্ড গেমিং হেডসেট সাথে নয়েজ-ক্যানসেলিং মাইক্রোফোন।',
    specs: ['7.1 Surround Sound', 'RGB Lighting', 'Noise Canceling Mic'],
  },
  {
    id: 'prod-9',
    name: 'Havit H2008d RGB 3.5mm Gaming Headset',
    nameBn: 'হ্যাভিট H2008d আরজিবি ৩.৫মিমি গেমিং হেডসেট',
    category: 'headphones',
    categoryBn: 'হেডফোন',
    price: 1950,
    originalPrice: 2600,
    discountBadge: '-25%',
    rating: 4.7,
    reviewCount: 56,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: false,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    description: 'Lightweight high-fidelity gaming headset with detachable HD mic.',
    descriptionBn: 'লাইটওয়েট হাই-ফাই গেমিং হেডসেট সাথে ডিটেচেবল এইচডি মাইক।',
    specs: ['50mm Drivers', 'Detachable Microphone', 'Soft Memory Foam Cushion'],
  },
  {
    id: 'prod-17',
    name: 'Razer BlackShark V2 X Gaming Headset',
    nameBn: 'রেজার ব্ল্যাকশার্ক V2 X গেমিং হেডসেট',
    category: 'headphones',
    categoryBn: 'হেডফোন',
    price: 4800,
    originalPrice: 5800,
    discountBadge: '-17%',
    rating: 4.9,
    reviewCount: 210,
    image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    description: 'Multi-platform esports gaming headset with TriForce 50mm drivers and HyperClear Cardioid mic.',
    descriptionBn: 'ট্রাইফোর্স ৫০মিমি ড্রাইভার সহ অফিসিয়াল ইস্পোর্টস হেডসেট।',
    specs: ['TriForce 50mm Drivers', 'HyperClear Cardioid Mic', 'Advanced Passive Noise Cancellation'],
  },
  {
    id: 'prod-18',
    name: 'Logitech G435 Lightspeed Wireless Gaming Headset',
    nameBn: 'লজিটেক G435 লাইটস্পিড ওয়ারলেস হেডসেট',
    category: 'headphones',
    categoryBn: 'হেডফোন',
    price: 6500,
    originalPrice: 7900,
    discountBadge: '-18%',
    rating: 4.8,
    reviewCount: 95,
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    description: 'Ultra-lightweight wireless gaming headset with 18 hours battery life and Bluetooth.',
    descriptionBn: '১৮ ঘণ্টা ব্যাটারি লাইফ সহ আল্ট্রা-লাইটওয়েট ওয়ারলেস গেমিং হেডসেট।',
    specs: ['Lightspeed Wireless + BT', '165g Ultra Lightweight', '18 Hours Battery'],
  },

  // 2. Gaming Mice
  {
    id: 'prod-2',
    name: 'Razer DeathAdder Essential Gaming Mouse',
    nameBn: 'রেজার ডেথঅ্যাডার এসেনশিয়াল গেমিং মাউস',
    category: 'mice',
    categoryBn: 'গেমিং মাউস',
    price: 1850,
    originalPrice: 2500,
    discountBadge: '-26%',
    rating: 4.8,
    reviewCount: 98,
    image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    description: 'Ergonomic gaming mouse with 6,400 DPI optical sensor and 5 programmable buttons.',
    descriptionBn: '৬,৪০০ ডিপিআই অপটিক্যাল সেন্সর সহ আর্গোনোমিক গেমিং মাউস।',
    specs: ['6400 DPI Optical Sensor', '5 Hyperesponse Buttons', '10 Million Clicks Lifetime'],
  },
  {
    id: 'prod-10',
    name: 'Logitech G102 Lightsync RGB Gaming Mouse',
    nameBn: 'লজিটেক G102 লাইটসিঙ্ক আরজিবি গেমিং মাউস',
    category: 'mice',
    categoryBn: 'গেমিং মাউস',
    price: 2150,
    originalPrice: 2700,
    discountBadge: '-20%',
    rating: 4.9,
    reviewCount: 280,
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: true,
    description: 'Classic 6-button gaming mouse with customizable 8,000 DPI gaming-grade sensor.',
    descriptionBn: '৮,০০০ ডিপিআই গেমিং সেন্সর ও ৮ মিলিয়ন কাস্টম ব্যাকলাইট সহ ক্লাসিক মাউস।',
    specs: ['8000 DPI Sensor', 'Lightsync RGB Color Wave', '6 Programmable Buttons'],
  },
  {
    id: 'prod-19',
    name: 'Fantech World VX7 Crypto Gaming Mouse',
    nameBn: 'ফ্যানটেক ওয়ার্ল্ড VX7 ক্রিপ্টো গেমিং মাউস',
    category: 'mice',
    categoryBn: 'গেমিং মাউস',
    price: 950,
    originalPrice: 1400,
    discountBadge: '-32%',
    rating: 4.6,
    reviewCount: 165,
    image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: false,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    description: 'Budget esports gaming mouse with 8000 DPI and 10 million click lifetime.',
    descriptionBn: 'বাজেট ফ্রেন্ডলি ৮০০০ ডিপিআই গেমিং মাউস।',
    specs: ['8000 DPI Sensor', 'RGB Lighting', 'Braided Cable'],
  },
  {
    id: 'prod-20',
    name: 'Glorious Model O Wireless Gaming Mouse',
    nameBn: 'গ্লোরিয়াস মডেল ও ওয়ারলেস গেমিং মাউস',
    category: 'mice',
    categoryBn: 'গেমিং মাউস',
    price: 6800,
    originalPrice: 8200,
    discountBadge: '-17%',
    rating: 5.0,
    reviewCount: 88,
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    description: 'Ultra-lightweight 69g honeycomb wireless gaming mouse with BAMF sensor.',
    descriptionBn: '৬৯ গ্রাম আল্ট্রা-লাইটওয়েট হানিকম্ব ওয়ারলেস গেমিং মাউস।',
    specs: ['BAMF 19k DPI Sensor', '69g Honeycomb Shell', '71 Hours Battery'],
  },

  // 3. Mechanical Keyboards
  {
    id: 'prod-3',
    name: 'Redragon K552 RGB Mechanical Gaming Keyboard',
    nameBn: 'রেড্রাগন K552 আরজিবি মেকানিক্যাল গেমিং কীবোর্ড',
    category: 'keyboards',
    categoryBn: 'কীবোর্ড',
    price: 3600,
    originalPrice: 4500,
    discountBadge: '-20%',
    rating: 4.9,
    reviewCount: 215,
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    description: 'Compact 87 key mechanical keyboard with custom dustproof switches and rainbow backlighting.',
    descriptionBn: 'কমপ্যাক্ট ৮৭ কী মেকানিক্যাল কীবোর্ড সাথে ডাস্টপ্রুফ সুইচ ও আরজিবি ব্যাকলাইট।',
    specs: ['Custom Blue Switches', 'Rainbow RGB Modes', 'Metal Alloy Frame'],
  },
  {
    id: 'prod-11',
    name: 'AULA F75 Wireless Tri-Mode Mechanical Keyboard',
    nameBn: 'আউলা F75 ওয়্যারলেস ট্রাই-মোড মেকানিক্যাল কীবোর্ড',
    category: 'keyboards',
    categoryBn: 'কীবোর্ড',
    price: 5200,
    originalPrice: 6500,
    discountBadge: '-20%',
    rating: 5.0,
    reviewCount: 74,
    image: 'https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: true,
    description: 'Hot-swappable gasket mount 75% mechanical keyboard with Reaper Linear switches.',
    descriptionBn: 'হট-সোয়াপ্যাবল গ্যাস্কেট মাউন্ট ৭৫% মেকানিক্যাল কীবোর্ড।',
    specs: ['Gasket Mount Structure', 'Tri-Mode Wireless/BT/Type-C', 'Pre-lubed Reaper Switches'],
  },
  {
    id: 'prod-21',
    name: 'E-YOOSO Z-11 RGB 60% Mechanical Keyboard',
    nameBn: 'ই-ইউসো Z-11 আরজিবি ৬০% মেকানিক্যাল কীবোর্ড',
    category: 'keyboards',
    categoryBn: 'কীবোর্ড',
    price: 2450,
    originalPrice: 3200,
    discountBadge: '-23%',
    rating: 4.7,
    reviewCount: 130,
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: false,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    description: 'Compact 61-key portable mechanical keyboard with hot-swappable red switches.',
    descriptionBn: 'কমপ্যাক্ট ৬১-কী পোর্টেবল হট-সোয়াপ্যাবল মেকানিক্যাল কীবোর্ড।',
    specs: ['60% Compact Layout', 'Hot-Swappable Red Switches', 'Detachable Type-C Cable'],
  },
  {
    id: 'prod-22',
    name: 'Royal Kludge RK61 Dual Mode Wireless Keyboard',
    nameBn: 'রয়্যাল ক্লজ RK61 ডুয়াল মোড ওয়্যারলেস কীবোর্ড',
    category: 'keyboards',
    categoryBn: 'কীবোর্ড',
    price: 3850,
    originalPrice: 4800,
    discountBadge: '-20%',
    rating: 4.8,
    reviewCount: 190,
    image: 'https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    description: 'Bluetooth 5.1 & Type-C wired dual mode 60% mechanical gaming keyboard.',
    descriptionBn: 'ব্লুটুথ ও টাইপ-সি ওয়ারার্ড ডুয়াল মোড মেকানিক্যাল গেমিং কীবোর্ড।',
    specs: ['Bluetooth 5.1 + Wired', 'Multi-Device Pairing', 'Long Battery Life'],
  },

  // 4. Fast Chargers
  {
    id: 'prod-4',
    name: 'Baseus 65W GaN Fast Charger 3-Port Adapter',
    nameBn: 'বেসাস ৬৫ ওয়াট GaN ফাস্ট চার্জার ৩-পোর্ট এডাপ্টার',
    category: 'chargers',
    categoryBn: 'ফাস্ট চার্জার',
    price: 2100,
    originalPrice: 2800,
    discountBadge: '-25%',
    rating: 4.7,
    reviewCount: 84,
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: false,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    description: 'Ultra-fast GaN technology charger for gaming phones, tablets, and laptops.',
    descriptionBn: 'গেমিং ফোন, ট্যাবলেট এবং ল্যাপটপের জন্য অতি দ্রুত GaN টেকনোলজি চার্জার।',
    specs: ['65W Total Output', '2x Type-C + 1x USB-A', 'GaN3 Technology'],
  },
  {
    id: 'prod-12',
    name: 'UGREEN 100W GaN Fast Wall Charger',
    nameBn: 'ইউগ্রিন ১০০W GaN ফাস্ট ওয়াল চার্জার',
    category: 'chargers',
    categoryBn: 'ফাস্ট চার্জার',
    price: 3400,
    originalPrice: 4200,
    discountBadge: '-19%',
    rating: 4.9,
    reviewCount: 48,
    image: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: true,
    description: '4-port 100W fast desktop charger powering 2 laptops and 2 phones simultaneously.',
    descriptionBn: '১০০ ওয়াট ৪-পোর্ট ফাস্ট চার্জার ২ টি ল্যাপটপ এবং ২ টি ফোন একসাথে চার্জ করার জন্য।',
    specs: ['100W Max Output', '3x Type-C + 1x USB-A', 'Power Dispenser System'],
  },
  {
    id: 'prod-23',
    name: 'Anker 511 Charger Nano 20W Fast Adapter',
    nameBn: 'অ্যাঙ্কার ৫১১ চার্জার ন্যানো ২০W ফাস্ট এডাপ্টার',
    category: 'chargers',
    categoryBn: 'ফাস্ট চার্জার',
    price: 1150,
    originalPrice: 1500,
    discountBadge: '-23%',
    rating: 4.8,
    reviewCount: 140,
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: false,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    description: 'Ultra-compact 20W USB-C fast charger for iPhone and Android devices.',
    descriptionBn: 'আইফোন ও অ্যান্ড্রয়েডের জন্য আল্ট্রা-কমপ্যাক্ট ২০ ওয়াট ফাস্ট চার্জার।',
    specs: ['20W PD Output', 'Nano Size Design', 'ActiveShield Safety'],
  },

  // 5. Finger Sleeves
  {
    id: 'prod-5',
    name: 'PUBG / Free Fire Sweatproof Gaming Finger Sleeves (Pair)',
    nameBn: 'পাবজি / ফ্রি ফায়ার সোয়েটপ্রুফ গেমিং ফিঙ্গার স্লিক (জোড়া)',
    category: 'finger-sleeves',
    categoryBn: 'ফিঙ্গার স্লিক',
    price: 150,
    originalPrice: 250,
    discountBadge: '-40%',
    rating: 4.8,
    reviewCount: 310,
    image: 'https://images.unsplash.com/photo-1592840496694-26d035b52b48?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    description: 'High sensitivity conductive silver fiber touch screen gloves for smooth mobile gaming.',
    descriptionBn: 'মোবাইল গেমিংয়ের জন্য অত্যন্ত সংবেদনশীল সিলভার ফাইবার টাচস্ক্রিন ফিঙ্গার স্লিক।',
    specs: ['Ultra-dense Silver Fiber', 'Sweatproof & Breathable', 'High Touch Sensitivity'],
  },
  {
    id: 'prod-13',
    name: 'Flydigi WASP Feelers 5 Carbon Fiber Finger Sleeves',
    nameBn: 'ফ্লাইডিজি ওয়াস্প ফিল্ডার্স ৫ কার্বন ফাইবার ফিঙ্গার স্লিক',
    category: 'finger-sleeves',
    categoryBn: 'ফিঙ্গার স্লিক',
    price: 350,
    originalPrice: 500,
    discountBadge: '-30%',
    rating: 4.9,
    reviewCount: 120,
    image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: true,
    description: '18-needle glass silver thread gaming finger gloves for zero touch delay.',
    descriptionBn: 'জিরো টাচ ডিল এর জন্য ১৮-নিডল গ্লাস সিলভার থ্রেড গেমিং ফিঙ্গার স্লিক।',
    specs: ['Glass Silver Thread', 'Zero Touch Friction', 'Seamless Weaving'],
  },
  {
    id: 'prod-24',
    name: 'Memeing Silver Fiber Ultra-thin Finger Gloves',
    nameBn: 'মিমিং সিলভার ফাইবার আল্ট্রা-থিন ফিঙ্গার গ্লাভস',
    category: 'finger-sleeves',
    categoryBn: 'ফিঙ্গার স্লিক',
    price: 180,
    originalPrice: 280,
    discountBadge: '-35%',
    rating: 4.7,
    reviewCount: 75,
    image: 'https://images.unsplash.com/photo-1592840496694-26d035b52b48?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: false,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    description: 'Breathable elastic finger cots designed for mobile esports players.',
    descriptionBn: 'মোবাইল ইস্পোর্টস প্লেয়ারদের জন্য ড্রায়ি সেমলেস ফিঙ্গার স্লিক।',
    specs: ['Silver Fiber Blend', 'Sweat Absorbing', 'High Elasticity'],
  },

  // 6. Cables
  {
    id: 'prod-6',
    name: 'Anker PowerLine III USB-C to USB-C 100W Cable (6ft)',
    nameBn: 'অ্যাঙ্কার পাওয়ারলাইন III টাইপ-সি টু টাইপ-সি ১০০W কেবল',
    category: 'cables',
    categoryBn: 'কেবলস',
    price: 1250,
    originalPrice: 1600,
    discountBadge: '-22%',
    rating: 4.9,
    reviewCount: 65,
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: false,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    description: 'Ultra-durable fast charging & data transfer cable with reinforced bulletproof fiber.',
    descriptionBn: 'অত্যন্ত টেকসই ১০০ ওয়াট ফাস্ট চার্জিং ও ডেটা ট্রান্সফার কেবল।',
    specs: ['100W Power Delivery', '25,000+ Bends Lifespan', 'E-Marker Chip Inside'],
  },
  {
    id: 'prod-14',
    name: 'Essager 100W LED Display Fast Charging Cable',
    nameBn: 'এসেজার ১০০W এলইডি ডিসপ্লে ফাস্ট চার্জিং কেবল',
    category: 'cables',
    categoryBn: 'কেবলস',
    price: 850,
    originalPrice: 1200,
    discountBadge: '-29%',
    rating: 4.8,
    reviewCount: 92,
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: true,
    description: 'Digital power display Type-C fast charging cable showing live wattage.',
    descriptionBn: 'লাইভ ওয়াটেজ দেখার জন্য ডিজিটাল পাওয়ার ডিসপ্লে টাইপ-সি ফাস্ট কেবল।',
    specs: ['Real-time Wattage Display', '100W PD Charging', 'High-density Braided Nylon'],
  },
  {
    id: 'prod-25',
    name: 'UGREEN 60W Right Angle Type-C Gaming Cable',
    nameBn: 'ইউগ্রিন ৬০W রাইট এঙ্গেল টাইপ-সি গেমিং কেবল',
    category: 'cables',
    categoryBn: 'কেবলস',
    price: 650,
    originalPrice: 900,
    discountBadge: '-28%',
    rating: 4.7,
    reviewCount: 110,
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: false,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    description: '90-degree elbow design Type-C cable for comfortable holding while gaming.',
    descriptionBn: 'গেমিং করার সময় সুবিধাজনকভাবে ধরার জন্য ৯০-ডিগ্রি এলবো টাইপ-সি কেবল।',
    specs: ['90-degree Right Angle', '60W Quick Charge', 'Durable Nylon Braid'],
  },

  // 7. Soundboxes
  {
    id: 'prod-7',
    name: 'JBL GO 3 Portable Bluetooth Soundbox',
    nameBn: 'জেবিএল গো ৩ পোর্টেবল ব্লুটুথ সাউন্ডবক্স',
    category: 'soundboxes',
    categoryBn: 'সাউন্ডবক্স',
    price: 3950,
    originalPrice: 4800,
    discountBadge: '-18%',
    rating: 4.8,
    reviewCount: 178,
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    description: 'IP67 waterproof compact Bluetooth speaker with powerful punchy bass.',
    descriptionBn: 'আইপি৬৭ ওয়াটারপ্রুফ কমপ্যাক্ট ব্লুটুথ স্পিকার সঙ্গে পাওয়ারফুল বেস।',
    specs: ['IP67 Waterproof & Dustproof', '5 Hours Playtime', 'Original JBL Pro Sound'],
  },
  {
    id: 'prod-15',
    name: 'Tronsmart Trip 10W Portable Speaker',
    nameBn: 'ট্রনস্মার্ট ট্রিপ ১০W পোর্টেবল স্পিকার',
    category: 'soundboxes',
    categoryBn: 'সাউন্ডবক্স',
    price: 1850,
    originalPrice: 2400,
    discountBadge: '-23%',
    rating: 4.7,
    reviewCount: 61,
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: false,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: true,
    description: 'Dual full-range drivers with passive radiator delivering unmatched clarity.',
    descriptionBn: 'ডুয়াল ফুল-রেঞ্জ ড্রাইভার সহ টেকসই ব্লুটুথ পোর্টেবল সাউন্ডবক্স।',
    specs: ['SoundPulse Audio', 'IPX7 Waterproof', '20 Hours Playtime'],
  },
  {
    id: 'prod-26',
    name: 'Lenovo K3 Pro Mini Wireless Bluetooth Speaker',
    nameBn: 'লেনোভো K3 প্রো মিনি ওয়্যারলেস ব্লুটুথ স্পিকার',
    category: 'soundboxes',
    categoryBn: 'সাউন্ডবক্স',
    price: 850,
    originalPrice: 1250,
    discountBadge: '-32%',
    rating: 4.6,
    reviewCount: 88,
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: false,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    description: 'Pocket-sized Bluetooth 5.0 speaker with 360-degree omnidirectional sound.',
    descriptionBn: '৩৬০-ডিগ্রি পোর্টেবল ব্লুটুথ ৫.০ পকেট স্পিকার।',
    specs: ['360 Omnidirectional Sound', 'Bluetooth 5.0', 'Built-in Mic for Calls'],
  },

  // 8. Trimmers
  {
    id: 'prod-8',
    name: 'Kemei KM-6330 Professional Hair & Beard Trimmer',
    nameBn: 'কিমি KM-৬৩৩০ প্রফেশনাল হেয়ার ও বিয়ার্ড ট্রিমার',
    category: 'trimmers',
    categoryBn: 'ট্রিমার',
    price: 990,
    originalPrice: 1500,
    discountBadge: '-34%',
    rating: 4.6,
    reviewCount: 94,
    image: 'https://images.unsplash.com/photo-1621607512214-68297480165e?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: false,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    description: 'Rechargeable precision grooming trimmer with stainless steel blades.',
    descriptionBn: 'স্টেইনলেস স্টিল ব্লেড সহ রিচার্জেবল প্রফেশনাল গ্রুমিং ট্রিমার।',
    specs: ['Rechargeable Battery', 'Stainless Steel Blade', 'Includes 3 Comb Attachments'],
  },
  {
    id: 'prod-16',
    name: 'VGR V-030 Professional Zero Cut Trimmer',
    nameBn: 'ভিজিআর V-০৩০ প্রফেশনাল জিরো কাট ট্রিমার',
    category: 'trimmers',
    categoryBn: 'ট্রিমার',
    price: 1350,
    originalPrice: 1900,
    discountBadge: '-29%',
    rating: 4.8,
    reviewCount: 110,
    image: 'https://images.unsplash.com/photo-1621607512214-68297480165e?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: true,
    description: 'Stainless steel T-blade zero gap cordless hair clipper with USB fast charge.',
    descriptionBn: 'স্টেইনলেস স্টিল টি-ব্লেড জিরো গ্যাপ কর্ডলেস বিয়ার্ড ট্রিমার।',
    specs: ['T-Blade Zero Cut', 'USB Fast Charge', '100 Mins Running Time'],
  },
  {
    id: 'prod-27',
    name: 'Vintage T9 Metal Skeleton Cordless Trimmer',
    nameBn: 'ভিন্টেজ T9 মেটাল স্কেলিটন কর্ডলেস ট্রিমার',
    category: 'trimmers',
    categoryBn: 'ট্রিমার',
    price: 650,
    originalPrice: 1100,
    discountBadge: '-41%',
    rating: 4.7,
    reviewCount: 220,
    image: 'https://images.unsplash.com/photo-1621607512214-68297480165e?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    description: 'Full metal dragon carved precision grooming clipper with rechargeable battery.',
    descriptionBn: 'ফুল মেটাল কার্ভড ড্রাগন বডি রিচার্জেবল বিয়ার্ড ট্রিমার।',
    specs: ['Full Metal Body', 'Zero Gap T-Blade', 'USB Rechargeable'],
  },
];
