import { Category, Product } from './types';

export const CATEGORIES: Category[] = [
  { id: 'headphones', name: 'Headphones', nameBn: 'হেডফোন', iconName: 'Headphones', itemCount: 24 },
  { id: 'mice', name: 'Gaming Mice', nameBn: 'গেমিং মাউস', iconName: 'Mouse', itemCount: 18 },
  { id: 'keyboards', name: 'Keyboards', nameBn: 'কীবোর্ড', iconName: 'Keyboard', itemCount: 15 },
  { id: 'chargers', name: 'Fast Chargers', nameBn: 'ফাস্ট চার্জার', iconName: 'Zap', itemCount: 32 },
  { id: 'finger-sleeves', name: 'Finger Sleeves', nameBn: 'ফিঙ্গার স্লিক', iconName: 'Hand', itemCount: 12 },
  { id: 'cables', name: 'Cables', nameBn: 'কেবলস', iconName: 'Cable', itemCount: 40 },
  { id: 'soundboxes', name: 'Soundboxes', nameBn: 'সাউন্ডবক্স', iconName: 'Speaker', itemCount: 16 },
  { id: 'trimmers', name: 'Trimmers', nameBn: 'ট্রিমার', iconName: 'Scissors', itemCount: 10 },
];

export const PRODUCTS: Product[] = [
  // 0. Gaming Coolers (Matching Reference Image 2)
  {
    id: 'prod-cooler-1',
    name: 'MEMO CX08 PRO PHONE COOLER',
    nameBn: 'মেমো CX08 প্রো ফোন কুলার',
    category: 'gaming-cooler',
    categoryBn: 'গেমিং কুলার',
    brand: 'MEMO',
    brandBn: 'মেমো',
    price: 1400,
    originalPrice: 1600,
    discountBadge: '-12%',
    rating: 4.9,
    reviewCount: 88,
    image: 'https://images.unsplash.com/photo-1592840496694-26d035b52b48?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: true,
    description: 'Semiconductor magnetic RGB cooling fan for PUBG & Mobile Gaming.',
    descriptionBn: 'পাবজি ও মোবাইল গেমিংয়ের জন্য আরজিবি কুলিং ফ্যান।',
    specs: ['Semiconductor Cooling', 'Magnetic Attachment', 'RGB Light Effects'],
  },
  {
    id: 'prod-cooler-2',
    name: 'MEMO CX14',
    nameBn: 'মেমো CX14 ফোন কুলার',
    category: 'gaming-cooler',
    categoryBn: 'গেমিং কুলার',
    brand: 'MEMO',
    brandBn: 'মেমো',
    price: 1380,
    originalPrice: 1500,
    discountBadge: '-8%',
    rating: 4.8,
    reviewCount: 64,
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: false,
    description: 'High-speed silent cooling fan with digital temperature display.',
    descriptionBn: 'ডিজিটাল ডিসপ্লে সহ হাই-স্পিড সাইলেন্ট কুলিং ফ্যান।',
    specs: ['Digital Temp Display', 'Silent Turbo Fan', 'Universal Clip'],
  },
  {
    id: 'prod-cooler-3',
    name: 'MEMO CX12',
    nameBn: 'মেমো CX12 মেকানিক কুলার',
    category: 'gaming-cooler',
    categoryBn: 'গেমিং কুলার',
    brand: 'MEMO',
    brandBn: 'মেমো',
    price: 1390,
    originalPrice: 1600,
    discountBadge: '-13%',
    rating: 4.7,
    reviewCount: 42,
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: false,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    description: 'Dual engine ice semiconductor phone cooler for heavy gaming.',
    descriptionBn: 'হেভি গেমিংয়ের জন্য ডুয়াল ইঞ্জিন আইস ফোন কুলার।',
    specs: ['Dual Cooling Engine', 'Yellow Accent Frame', 'USB Type-C Power'],
  },
  {
    id: 'prod-cooler-4',
    name: 'MEMO CX15',
    nameBn: 'মেমো CX15 স্পিড কুলার',
    category: 'gaming-cooler',
    categoryBn: 'গেমিং কুলার',
    brand: 'MEMO',
    brandBn: 'মেমো',
    price: 1270,
    originalPrice: 1450,
    discountBadge: '-12%',
    rating: 4.9,
    reviewCount: 95,
    image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    description: 'Ultra fast heat dissipation radiator fan for all smartphones.',
    descriptionBn: 'সব স্মার্টফোনের জন্য আল্ট্রা ফাস্ট কুলিং রেডিয়েটর ফ্যান।',
    specs: ['Rapid Heat Dissipation', 'Multi-color RGB Ring', 'Lightweight Design'],
  },

  // 1. Headphones
  {
    id: 'prod-1',
    name: 'Fantech HG11 Captain 7.1 Gaming Headset',
    nameBn: 'ফ্যানটেক HG11 ক্যাপ্টেন ৭.১ গেমিং হেডসেট',
    category: 'headphones',
    categoryBn: 'হেডফোন',
    brand: 'Fantech',
    brandBn: 'ফ্যানটেক',
    price: 2450,
    originalPrice: 3200,
    discountBadge: '-23%',
    rating: 4.9,
    reviewCount: 142,
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    description: 'High performance RGB surround sound gaming headset with noise-canceling microphone.',
    descriptionBn: 'উচ্চমানের আরজিবি সারাউন্ড সাউন্ড গেমিং হেডসেট সাথে নয়েজ-ক্যানসেলিং মাইক্রোফোন।',
    specs: ['7.1 Surround Sound', 'RGB Lighting', 'Noise Canceling Mic'],
  },
  {
    id: 'prod-9',
    name: 'Havit H2008d RGB 3.5mm Gaming Headset',
    nameBn: 'হ্যাভিট H2008d আরজিবি ৩.৫মিমি গেমিং হেডসেট',
    category: 'headphones',
    categoryBn: 'হেডফোন',
    brand: 'Havit',
    brandBn: 'হ্যাভিট',
    price: 1950,
    originalPrice: 2600,
    discountBadge: '-25%',
    rating: 4.7,
    reviewCount: 56,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: false,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    description: 'Lightweight high-fidelity gaming headset with detachable HD mic.',
    descriptionBn: 'লাইটওয়েট হাই-ফাই গেমিং হেডসেট সাথে ডিটেচেবল এইচডি মাইক।',
    specs: ['50mm Drivers', 'Detachable Microphone', 'Soft Memory Foam Cushion'],
  },
  {
    id: 'prod-17',
    name: 'Razer BlackShark V2 X Gaming Headset',
    nameBn: 'রেজার ব্ল্যাকশার্ক V2 X গেমিং হেডসেট',
    category: 'headphones',
    categoryBn: 'হেডফোন',
    brand: 'Razer',
    brandBn: 'রেজার',
    price: 4800,
    originalPrice: 5800,
    discountBadge: '-17%',
    rating: 4.9,
    reviewCount: 210,
    image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    description: 'Multi-platform esports gaming headset with TriForce 50mm drivers and HyperClear Cardioid mic.',
    descriptionBn: 'ট্রাইফোর্স ৫০মিমি ড্রাইভার সহ অফিসিয়াল ইস্পোর্টস হেডসেট।',
    specs: ['TriForce 50mm Drivers', 'HyperClear Cardioid Mic', 'Advanced Passive Noise Cancellation'],
  },

  // 2. Gaming Mice
  {
    id: 'prod-2',
    name: 'Razer DeathAdder Essential Gaming Mouse',
    nameBn: 'রেজার ডেথঅ্যাডার এসেনশিয়াল গেমিং মাউস',
    category: 'mice',
    categoryBn: 'গেমিং মাউস',
    brand: 'Razer',
    brandBn: 'রেজার',
    price: 1850,
    originalPrice: 2500,
    discountBadge: '-26%',
    rating: 4.8,
    reviewCount: 98,
    image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    description: 'Ergonomic gaming mouse with 6,400 DPI optical sensor and 5 programmable buttons.',
    descriptionBn: '৬,৪০০ ডিপিআই অপটিক্যাল সেন্সর সহ আর্গোনোমিক গেমিং মাউস।',
    specs: ['6400 DPI Optical Sensor', '5 Hyperesponse Buttons', '10 Million Clicks Lifetime'],
  },
  {
    id: 'prod-10',
    name: 'Logitech G102 Lightsync RGB Gaming Mouse',
    nameBn: 'লজিটেক G102 লাইটসিঙ্ক আরজিবি গেমিং মাউস',
    category: 'mice',
    categoryBn: 'গেমিং মাউস',
    brand: 'Logitech',
    brandBn: 'লজিটেক',
    price: 2150,
    originalPrice: 2700,
    discountBadge: '-20%',
    rating: 4.9,
    reviewCount: 280,
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: true,
    description: 'Classic 6-button gaming mouse with customizable 8,000 DPI gaming-grade sensor.',
    descriptionBn: '৮,০০০ ডিপিআই গেমিং সেন্সর ও ৮ মিলিয়ন কাস্টম ব্যাকলাইট সহ ক্লাসিক মাউস।',
    specs: ['8000 DPI Sensor', 'Lightsync RGB Color Wave', '6 Programmable Buttons'],
  },

  // 3. Mechanical Keyboards
  {
    id: 'prod-3',
    name: 'Redragon K552 RGB Mechanical Gaming Keyboard',
    nameBn: 'রেড্রাগন K552 আরজিবি মেকানিক্যাল গেমিং কীবোর্ড',
    category: 'keyboards',
    categoryBn: 'কীবোর্ড',
    brand: 'Redragon',
    brandBn: 'রেড্রাগন',
    price: 3600,
    originalPrice: 4500,
    discountBadge: '-20%',
    rating: 4.9,
    reviewCount: 215,
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    description: 'Compact 87 key mechanical keyboard with custom dustproof switches and rainbow backlighting.',
    descriptionBn: 'কমপ্যাক্ট ৮৭ কী মেকানিক্যাল কীবোর্ড সাথে ডাস্টপ্রুফ সুইচ ও আরজিবি ব্যাকলাইট।',
    specs: ['Custom Blue Switches', 'Rainbow RGB Modes', 'Metal Alloy Frame'],
  },
  {
    id: 'prod-11',
    name: 'AULA F75 Wireless Tri-Mode Mechanical Keyboard',
    nameBn: 'আউলা F75 ওয়্যারলেস ট্রাই-মোড মেকানিক্যাল কীবোর্ড',
    category: 'keyboards',
    categoryBn: 'কীবোর্ড',
    brand: 'AULA',
    brandBn: 'আউলা',
    price: 5200,
    originalPrice: 6500,
    discountBadge: '-20%',
    rating: 5.0,
    reviewCount: 74,
    image: 'https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: true,
    description: 'Hot-swappable gasket mount 75% mechanical keyboard with Reaper Linear switches.',
    descriptionBn: 'হট-সোয়াপ্যাবল গ্যাস্কেট মাউন্ট ৭৫% মেকানিক্যাল কীবোর্ড।',
    specs: ['Gasket Mount Structure', 'Tri-Mode Wireless/BT/Type-C', 'Pre-lubed Reaper Switches'],
  },

  // 4. Fast Chargers
  {
    id: 'prod-4',
    name: 'Baseus 65W GaN Fast Charger 3-Port Adapter',
    nameBn: 'বেসাস ৬৫ ওয়াট GaN ফাস্ট চার্জার ৩-পোর্ট এডাপ্টার',
    category: 'chargers',
    categoryBn: 'ফাস্ট চার্জার',
    brand: 'Baseus',
    brandBn: 'বেসাস',
    price: 2100,
    originalPrice: 2800,
    discountBadge: '-25%',
    rating: 4.7,
    reviewCount: 84,
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: false,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    description: 'Ultra-fast GaN technology charger for gaming phones, tablets, and laptops.',
    descriptionBn: 'গেমিং ফোন, ট্যাবলেট এবং ল্যাপটপের জন্য অতি দ্রুত GaN টেকনোলজি চার্জার।',
    specs: ['65W Total Output', '2x Type-C + 1x USB-A', 'GaN3 Technology'],
  },

  // 5. Finger Sleeves
  {
    id: 'prod-5-1',
    name: 'Flydigi WASP Feelers 5 Carbon Fiber Finger Sleeves (Pair)',
    nameBn: 'ফ্লাইডিজি ওয়াজ্প ফিঙ্গার স্লিকস (জোড়া)',
    category: 'finger-sleeves',
    categoryBn: 'ফিঙ্গার স্লিক',
    brand: 'Flydigi',
    brandBn: 'ফ্লাইডিজি',
    price: 180,
    originalPrice: 280,
    discountBadge: '-35%',
    rating: 4.9,
    reviewCount: 420,
    image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    description: 'High sensitivity 18-needle carbon fiber touch screen sleeves for PUBG Mobile & Free Fire.',
    descriptionBn: 'পাবজি ও ফ্রি ফায়ারের জন্য ১৮-নিডেল কার্বন ফাইবার টাচস্ক্রিন স্লিক।',
    specs: ['18-Needle Carbon Fiber', 'Zero Friction', 'Sweatproof & Breathable'],
  },
  {
    id: 'prod-5-2',
    name: 'MEMO Gaming Sweatproof Glass Silver Fiber Sleeves (2 Pairs)',
    nameBn: 'মেমো গেমিং গ্লাস সিলভার ফিঙ্গার স্লিকস (২ জোড়া)',
    category: 'finger-sleeves',
    categoryBn: 'ফিঙ্গার স্লিক',
    brand: 'MEMO',
    brandBn: 'মেমো',
    price: 250,
    originalPrice: 380,
    discountBadge: '-34%',
    rating: 4.8,
    reviewCount: 210,
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    description: 'Ultra thin 0.3mm silver conductive fiber gloves for maximum touch responsiveness.',
    descriptionBn: '০.৩মিমি আল্ট্রা থিন সিলভার ফাইবার গেমিং স্লিকস।',
    specs: ['0.3mm Ultra Thin', '2-Pair Value Pack', 'High Elasticity Fit'],
  },

  // 6. Gaming Earphones
  {
    id: 'prod-ear-1',
    name: 'Plextone G20 Mark IV Gaming Earphone with Mic',
    nameBn: 'প্লেক্সটোন G20 মার্ক IV গেমিং ইয়ারফোন',
    category: 'gaming-earphone',
    categoryBn: 'গেমিং ইয়ারফোন',
    brand: 'Plextone',
    brandBn: 'প্লেক্সটোন',
    price: 890,
    originalPrice: 1250,
    discountBadge: '-28%',
    rating: 4.8,
    reviewCount: 155,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    description: 'Dual bass magnetic gaming in-ear headset with long noise canceling microphone.',
    descriptionBn: 'ডুয়াল বেস ম্যাগনেটিক ইন-ইয়ার গেমিং ইয়ারফোন।',
    specs: ['Dual Bass Engine', 'Magnetic Earbud Lock', '3.5mm L-Shape Jack'],
  },
  {
    id: 'prod-ear-2',
    name: 'QKZ AK6 Pro HiFi In-Ear Gaming Headphones',
    nameBn: 'QKZ AK6 প্রো হাইফাই গেমিং ইয়ারফোন',
    category: 'gaming-earphone',
    categoryBn: 'গেমিং ইয়ারফোন',
    brand: 'QKZ',
    brandBn: 'কিউকেজেড',
    price: 490,
    originalPrice: 750,
    discountBadge: '-34%',
    rating: 4.7,
    reviewCount: 98,
    image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: false,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    description: 'Detachable cable copper driver HiFi earphone for mobile gaming.',
    descriptionBn: 'ডিটেচেবল কেবল প্রিমিয়াম হাইফাই গেমিং ইয়ারফোন।',
    specs: ['Detachable Cable', 'Copper Driver Unit', 'HD Microphone'],
  },

  // 7. Gaming Powder
  {
    id: 'prod-pow-1',
    name: 'Flydigi Sweatproof Gaming Powder (50g)',
    nameBn: 'ফ্লাইডিজি সোয়েটপ্রুফ গেমিং পাউডার (৫০ গ্রাম)',
    category: 'gaming-powder',
    categoryBn: 'গেমিং পাউডার',
    brand: 'Flydigi',
    brandBn: 'ফ্লাইডিজি',
    price: 350,
    originalPrice: 500,
    discountBadge: '-30%',
    rating: 4.9,
    reviewCount: 88,
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    description: 'Dry hand frictionless powder for competitive mobile gamers.',
    descriptionBn: 'মোবাইল গেমারদের জন্য ড্রাই হ্যান্ড গেমিং পাউডার।',
    specs: ['Frictionless Glide', 'Moisture Absorbing', 'Non-Toxic Formula'],
  },

  // 8. Magnetic Plates
  {
    id: 'prod-mag-1',
    name: 'MEMO Magnetic Metal Plate Sheet for Phone Cooler',
    nameBn: 'মেমো ম্যাগনেটিক মেটাল প্লেট শীট',
    category: 'magnetic-plates',
    categoryBn: 'ম্যাগনেটিক প্লেটস',
    brand: 'MEMO',
    brandBn: 'মেমো',
    price: 190,
    originalPrice: 300,
    discountBadge: '-36%',
    rating: 4.8,
    reviewCount: 140,
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    description: 'Universal thermal conductive sticker for magnetic phone coolers.',
    descriptionBn: 'ম্যাগনেটিক কুলারের জন্য থার্মাল কন্ডাক্টিভ মেটাল স্টিকার।',
    specs: ['Strong Magnetic Grip', 'Thermal Transfer Sheet', 'Scratchless Adhesive'],
  },

  // 9. Gaming Triggers
  {
    id: 'prod-trig-1',
    name: 'MEMO AK66 PUBG Mobile Gaming Trigger Controller',
    nameBn: 'মেমো AK66 পাবজি গেমিং ট্রিগার কন্ট্রোলার',
    category: 'gaming-triggers',
    categoryBn: 'গেমিং ট্রিগার',
    brand: 'MEMO',
    brandBn: 'মেমো',
    price: 450,
    originalPrice: 650,
    discountBadge: '-30%',
    rating: 4.8,
    reviewCount: 230,
    image: 'https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    description: '4-trigger ergonomic mechanical gamepad handle for PUBG & Free Fire.',
    descriptionBn: '৪-ট্রিগার আর্গোনোমিক গেমিং গ্রিপ কন্ট্রোলার।',
    specs: ['4 Triggers 6-Finger Control', 'Sensitive Metal Contact', 'Foldable Grip'],
  },

  // 10. Power Bank
  {
    id: 'prod-pb-1',
    name: 'Baseus Adaman 20000mAh 65W Fast Charging Power Bank',
    nameBn: 'বেসাস আডামান ২০০০০mAh ৬৫W পাওয়ার ব্যাংক',
    category: 'power-bank',
    categoryBn: 'পাওয়ার ব্যাংক',
    brand: 'Baseus',
    brandBn: 'বেসাস',
    price: 3950,
    originalPrice: 4800,
    discountBadge: '-18%',
    rating: 4.9,
    reviewCount: 165,
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    description: 'Metal body 65W PD fast charging power bank for laptops and gaming phones.',
    descriptionBn: 'ল্যাপটপ ও গেমিং ফোনের জন্য মেটাল বডি ৬৫W ফাস্ট চার্জিং পাওয়ার ব্যাংক।',
    specs: ['20000mAh Capacity', '65W Power Delivery', 'Digital Display Status'],
  },

  // 11. Charger Adapter
  {
    id: 'prod-chg-1',
    name: 'UGREEN 100W 4-Port GaN Fast Charger Adapter',
    nameBn: 'ইউগ্রিন ১০০W ৪-পোর্ট GaN ফাস্ট চার্জার ایڈাপ্টার',
    category: 'charger-adapter',
    categoryBn: 'চার্জার এডাপ্টার',
    brand: 'UGREEN',
    brandBn: 'ইউগ্রিন',
    price: 3450,
    originalPrice: 4200,
    discountBadge: '-18%',
    rating: 4.9,
    reviewCount: 88,
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: true,
    description: 'Quad-port desktop GaN wall charger with multi-device fast charge technology.',
    descriptionBn: '৪-পোর্ট GaN ফাস্ট ওয়াল চার্জার এডাপ্টার।',
    specs: ['100W Max Output', '3x Type-C + 1x USB-A', 'GaN Fast Safety Tech'],
  },

  // 6. Cables
  {
    id: 'prod-6',
    name: 'Anker PowerLine III USB-C to USB-C 100W Cable (6ft)',
    nameBn: 'অ্যাঙ্কার পাওয়ারলাইন III টাইপ-সি টু টাইপ-সি ১০০W কেবল',
    category: 'cables',
    categoryBn: 'কেবলস',
    brand: 'Anker',
    brandBn: 'অ্যাঙ্কার',
    price: 1250,
    originalPrice: 1600,
    discountBadge: '-22%',
    rating: 4.9,
    reviewCount: 65,
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: false,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    description: 'Ultra-durable fast charging & data transfer cable with reinforced bulletproof fiber.',
    descriptionBn: 'অত্যন্ত টেকসই ১০০ ওয়াট ফাস্ট চার্জিং ও ডেটা ট্রান্সফার কেবল।',
    specs: ['100W Power Delivery', '25,000+ Bends Lifespan', 'E-Marker Chip Inside'],
  },

  // 7. Soundboxes
  {
    id: 'prod-7',
    name: 'JBL GO 3 Portable Bluetooth Soundbox',
    nameBn: 'জেবিএল গো ৩ পোর্টেবল ব্লুটুথ সাউন্ডবক্স',
    category: 'soundboxes',
    categoryBn: 'সাউন্ডবক্স',
    brand: 'JBL',
    brandBn: 'জেবিএল',
    price: 3950,
    originalPrice: 4800,
    discountBadge: '-18%',
    rating: 4.8,
    reviewCount: 178,
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: true,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    description: 'IP67 waterproof compact Bluetooth speaker with powerful punchy bass.',
    descriptionBn: 'আইপি৬৭ ওয়াটারপ্রুফ কমপ্যাক্ট ব্লুটুথ স্পিকার সঙ্গে পাওয়ারফুল বেস।',
    specs: ['IP67 Waterproof & Dustproof', '5 Hours Playtime', 'Original JBL Pro Sound'],
  },

  // 8. Trimmers
  {
    id: 'prod-8',
    name: 'Kemei KM-6330 Professional Hair & Beard Trimmer',
    nameBn: 'কিমি KM-৬৩৩০ প্রফেশনাল হেয়ার ও বিয়ার্ড ট্রিমার',
    category: 'trimmers',
    categoryBn: 'ট্রিমার',
    brand: 'Kemei',
    brandBn: 'কিমি',
    price: 990,
    originalPrice: 1500,
    discountBadge: '-34%',
    rating: 4.6,
    reviewCount: 94,
    image: 'https://images.unsplash.com/photo-1621607512214-68297480165e?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    isPopular: false,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    description: 'Rechargeable precision grooming trimmer with stainless steel blades.',
    descriptionBn: 'স্টেইনলেস স্টিল ব্লেড সহ রিচার্জেবল প্রফেশনাল গ্রুমিং ট্রিমার।',
    specs: ['Rechargeable Battery', 'Stainless Steel Blade', 'Includes 3 Comb Attachments'],
  },
];

// Exclusive COMBO OFFER Bundle Products with multi-product images
export const COMBO_PRODUCTS: Product[] = [
  {
    id: 'combo-1',
    name: 'Esports Gamer Pro Bundle: RGB Keyboard + Mouse + Gaming Pad',
    nameBn: 'ইস্পোর্টস গেমার প্রো বান্ডেল: মেকানিক্যাল কীবোর্ড + গেমিং মাউস + মাউসপ্যাড',
    category: 'keyboards',
    categoryBn: 'কম্বো অফার',
    brand: 'Redragon',
    brandBn: 'রেড্রাগন',
    price: 3990,
    originalPrice: 6200,
    discountBadge: '-36% OFF',
    rating: 5.0,
    reviewCount: 185,
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80',
    comboImages: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=400&q=80',
      'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=400&q=80',
      'https://images.unsplash.com/photo-1547394765-185e1e68f34e?auto=format&fit=crop&w=400&q=80',
    ],
    inStock: true,
    isPopular: true,
    isComboOffer: true,
    soldCount: 185,
    description: 'Ultimate esports gaming starter combo featuring RGB mechanical keyboard, high precision 6400 DPI mouse, and speed mousepad.',
    descriptionBn: 'মেকানিক্যাল কীবোর্ড, অপটিক্যাল মাউস এবং স্পিড মাউসপ্যাডের আল্টিমেট ইস্পোর্টস গেমার কম্বো অফার।',
    specs: ['Redragon RGB Mechanical Keyboard', 'Razer 6400 DPI Gaming Mouse', 'Extra Large Speed Gaming Mat'],
  },
  {
    id: 'combo-2',
    name: 'PUBG Mobile Pro Combo: Finger Sleeves 3-Pack + 65W Fast Charger + Braided Cable',
    nameBn: 'পাবজি মোবাইল প্রো কম্বো: ফিঙ্গার স্লিক ৩-প্যাক + ৬৫W চার্জার + কেবল',
    category: 'finger-sleeves',
    categoryBn: 'কম্বো অফার',
    brand: 'Baseus',
    brandBn: 'বেসাস',
    price: 1450,
    originalPrice: 2500,
    discountBadge: '-42% OFF',
    rating: 4.9,
    reviewCount: 320,
    image: 'https://images.unsplash.com/photo-1592840496694-26d035b52b48?auto=format&fit=crop&w=600&q=80',
    comboImages: [
      'https://images.unsplash.com/photo-1592840496694-26d035b52b48?auto=format&fit=crop&w=400&q=80',
      'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=400&q=80',
      'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=400&q=80',
    ],
    inStock: true,
    isPopular: true,
    isComboOffer: true,
    soldCount: 320,
    description: 'Everything you need for zero latency PUBG/Free-Fire mobile gaming with fast charging support.',
    descriptionBn: 'মোবাইল গেমিংয়ের সেরা কম্বো: ৩ জোড়া ফাইবার স্লিকস, ফাস্ট চার্জার এবং ১০০W টাইপ-সি কেবল।',
    specs: ['3 Pairs Silver Fiber Finger Sleeves', 'Baseus GaN 65W Fast Charger', 'Anker PowerLine Type-C Cable'],
  },
  {
    id: 'combo-3',
    name: 'Ultimate Audio Duo: 7.1 RGB Gaming Headset + Portable Soundbox Speaker',
    nameBn: 'আল্টিমেট অডিও ডুও: ৭.১ আরজিবি হেডসেট + পোর্টেবল সাউন্ডবক্স স্পিকার',
    category: 'headphones',
    categoryBn: 'কম্বো অফার',
    brand: 'Fantech',
    brandBn: 'ফ্যানটেক',
    price: 5250,
    originalPrice: 8000,
    discountBadge: '-34% OFF',
    rating: 4.9,
    reviewCount: 142,
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=600&q=80',
    comboImages: [
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=400&q=80',
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=400&q=80',
    ],
    inStock: true,
    isPopular: true,
    isComboOffer: true,
    soldCount: 142,
    description: 'Crystal clear surround sound for gaming and punchy portable bass for outdoor entertainment.',
    descriptionBn: 'ফ্যানটেক ক্যাপ্টেন ৭.১ গেমিং হেডসেট ও জেবিএল গো ৩ সাউন্ডবক্স স্পিকারের সেরা কম্বো।',
    specs: ['7.1 Surround RGB Headset', 'IP67 Waterproof Bluetooth Speaker', 'Official Warranty Included'],
  },
  {
    id: 'combo-4',
    name: 'Streamer Pro Bundle: Tri-Mode Wireless Keyboard + Lightweight RGB Mouse',
    nameBn: 'স্ট্রিমার প্রো বান্ডেল: ওয়্যারলেস মেকানিক্যাল কীবোর্ড + আরজিবি মাউস',
    category: 'keyboards',
    categoryBn: 'কম্বো অফার',
    brand: 'AULA',
    brandBn: 'আউলা',
    price: 6990,
    originalPrice: 10500,
    discountBadge: '-33% OFF',
    rating: 5.0,
    reviewCount: 96,
    image: 'https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=600&q=80',
    comboImages: [
      'https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=400&q=80',
      'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=400&q=80',
    ],
    inStock: true,
    isPopular: true,
    isComboOffer: true,
    soldCount: 96,
    description: 'Pro streamer workspace setup with hot-swappable gasket mount wireless keyboard & RGB mouse.',
    descriptionBn: 'আউলা F75 ট্রাই-মোড ওয়্যারলেস কীবোর্ড এবং লজিটেক G102 গেমিং মাউসের প্রিমিয়াম কম্বো।',
    specs: ['AULA F75 Wireless Gasket Keyboard', 'Logitech G102 Lightsync Mouse', 'RGB Synchronization'],
  },
  {
    id: 'combo-5',
    name: 'Grooming & Fast Power Kit: KM-6330 Trimmer + 100W GaN Desktop Charger',
    nameBn: 'গ্রুমিং ও ফাস্ট পাওয়ার কিট: ট্রিমার + ১০০W ফাস্ট ওয়াল চার্জার',
    category: 'trimmers',
    categoryBn: 'কম্বো অফার',
    brand: 'Kemei',
    brandBn: 'কিমি',
    price: 2750,
    originalPrice: 4300,
    discountBadge: '-36% OFF',
    rating: 4.8,
    reviewCount: 210,
    image: 'https://images.unsplash.com/photo-1621607512214-68297480165e?auto=format&fit=crop&w=600&q=80',
    comboImages: [
      'https://images.unsplash.com/photo-1621607512214-68297480165e?auto=format&fit=crop&w=400&q=80',
      'https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=400&q=80',
    ],
    inStock: true,
    isPopular: false,
    isComboOffer: true,
    soldCount: 210,
    description: 'Heavy duty rechargeable beard trimmer paired with 100W 4-port multi-device fast charger.',
    descriptionBn: 'কিমি প্রফেশনাল হেয়ার ও বিয়ার্ড ট্রিমার এবং ইউগ্রিন ১০০W ফাস্ট চার্জারের কম্বো প্যাক।',
    specs: ['KM-6330 Precision Trimmer', '100W 4-Port GaN Desktop Charger', 'USB Charging Accessories'],
  },
  {
    id: 'combo-6',
    name: 'Mobile Gamer Speed Pack: Flydigi Carbon Sleeves + 90° Elbow Fast Cable',
    nameBn: 'মোবাইল গেমার স্পিড প্যাক: কার্বন ফাইবার স্লিক + ৯০° এলবো টাইপ-সি কেবল',
    category: 'finger-sleeves',
    categoryBn: 'কম্বো অফার',
    brand: 'Flydigi',
    brandBn: 'ফ্লাইডিজি',
    price: 990,
    originalPrice: 1650,
    discountBadge: '-40% OFF',
    rating: 4.9,
    reviewCount: 285,
    image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=600&q=80',
    comboImages: [
      'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=400&q=80',
      'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=400&q=80',
    ],
    inStock: true,
    isPopular: true,
    isComboOffer: true,
    soldCount: 285,
    description: 'Designed specifically for competitive mobile gamers needing zero friction and comfortable grip while charging.',
    descriptionBn: 'ফ্লাইডিজি গ্লাস সিলভার স্লিকস ২-জোড়া এবং ইউগ্রিন ৯০-ডিগ্রি গেমিং টাইপ-সি কেবলের স্পেশাল ডিল।',
    specs: ['Flydigi WASP 2 Pairs Sleeves', 'UGREEN 60W Right Angle Cable', 'Zero Latency Performance'],
  },
];

export const getBrandName = (product?: Partial<Product> | null, language: string = 'en'): string => {
  if (!product) return 'Mex Tanim';
  if (language === 'bn' && product.brandBn) return product.brandBn;
  if (product.brand) return product.brand;
  if (product.name) {
    const firstWord = product.name.trim().split(' ')[0];
    if (firstWord && firstWord.length > 1) return firstWord;
  }
  return 'Mex Tanim';
};
